### ISSUE TITLE
请问下7万，10万这些dict是怎么切出来的

### ISSUE THREAD

**Issue by xnile** [cliuxinxin/TX-WORD2VEC-SMALL#2]
想知道下7万，10万这些次是怎样切出来的

**Comment by cliuxinxin** [comment]
非常简单，就是简单的读取文件，一行一行的读，循环7w次，就切出7w的词了，循环10w次，就切出了10w的词了。

我想这个应该解答了你的问题。我我先关闭了。如果有进一步的问题，可以另开问题或者打开这问题
