### ISSUE TITLE
希望贡献一份自己的版本

### ISSUE THREAD

**Issue by Python-37** [cliuxinxin/TX-WORD2VEC-SMALL#4]
你好，我目前在做自然语言这一块，并且在使用腾讯的库，前段时间已经把这个15.6G的文件转换成内存映射形式，缩小到7G，但是我使用的是Linux，无法上传到百度云，所以希望借此项目分享自己作出的一点成果，不知道如何将模型文件传给你，或者想办法将编译过程代码分享出来。

**Comment by Inspiring26** [comment]
可以qq邮箱超大附件给我，我帮你上传。联系邮箱：1002990258@qq.com

**Comment by kawa23** [comment]
Hi, I can't find the 7G compress version at the README, where can i get it? thx

**Comment by guoruibiao** [comment]
> d the 7G compress version at the README, where can i get it? thx

太秀了大兄弟

**Comment by cliuxinxin** [comment]
> 你好，我目前在做自然语言这一块，并且在使用腾讯的库，前段时间已经把这个15.6G的文件转换成内存映射形式，缩小到7G，但是我使用的是Linux，无法上传到百度云，所以希望借此项目分享自己作出的一点成果，不知道如何将模型文件传给你，或者想办法将编译过程代码分享出来。

我居然木有收到通知，真是太废了，如果你还在弄的话，可以fork以后做个新的版本，pull给我，我accept就可以了。哈哈哈，不知道2年后的回复会不会晚。

**Comment by Python-37** [comment]
> 我居然木有收到通知，真是太废了，如果你还在弄的话，可以fork以后做个新的版本，pull给我，我accept就可以了。哈哈哈，不知道2年后的回复会不会晚。

我已经从两年前那家公司离职，并且现在在做图像算法，当时的文件和代码都属于前公司了。
当时还给gensim的开发者提过  issue RaRe-Technologies/gensim/issues/2447 问这个问题。
这个问题是在[这里](https://stackoverflow.com/questions/42986405/how-to-speed-up-gensim-word2vec-model-load-time/43067907)找到的答案，具体怎么写已经记不得了😂

**Comment by cliuxinxin** [comment]
Github 的通知策略不是很好，不能及时的通知到我，结果造成了大家的损失。这个锅算我的。
