### ISSUE TITLE
网盘失效了，可以在分享下么？

### ISSUE THREAD

**Issue by oncealong** [cliuxinxin/TX-WORD2VEC-SMALL#8]
2000000-small.txt 200w词 3.8GB 链接: https://pan.baidu.com/s/12Ygkgo3J9cq4hWV8NiucSQ?pwd=63gs 提取码: 63gs
---
网盘失效了，楼主可以在分享下么？

**Comment by cliuxinxin** [comment]
OK，已经更新。
